exampleSite/config.toml
Remove [params.defaultImage.article] and [params.defaultImage.articleList] from config.toml
Those configs still works, but I do not encourage its usage.
=> refactor(config): deprecate article default image

exampleSite/content/page/about.md, i18n/en.toml, i18n/zh-CN.toml, layouts/partials/article/components/footer.html
> can't evaluate field Count in type string
Count could not be displayed when using `.Count`, so this has been changed.
=> fix(article): last updated time error

exampleSite/content/post/chinese-test/index.md, exampleSite/content/post/placeholder-text/index.md, layouts/partials/article/components/details.html, layouts/partials/article/components/tags.html, layouts/partials/widget/tag-cloud.html
Hello,
Here is a small fix to call [`urlize`](https://gohugo.io/functions/urlize/) to get the category URL instead of using its name directly. Before this fix it was not working with categories containing special character or white spaces.
Best.
=> Fix categories with special char or spaces not displayed correctly

assets/scss/partials/layout/archives.scss, assets/scss/partials/layout/taxonomy.scss, assets/scss/partials/widgets.scss, assets/scss/style.scss, layouts/_default/archives.html, layouts/_default/term.html, layouts/partials/article/components/related-contents.html, layouts/partials/widget/archives.html, layouts/partials/widget/tag-cloud.html
For the small title before the card
Remove `.widget-title`, `.archive-date`, `.taxonomy-type` from SCSS, as they all share the same style.
=> Refactor: add .section-title

i18n/en.toml, i18n/fr.toml, layouts/partials/footer/footer.html
I didn't re-added translations of "posts" and "categories" title, I don't want to break taxonomies and cause problems with plurials terminations. So it's only some basics translations here.
=> i18n: added french translations & footer translation

exampleSite/config.toml, layouts/partials/sidebar/left.html
It's a bit ugly, but I did a test to fix the issue #50.
The actual problem is that GoHugo does not offer any conditionals to test if a variable is a URL, also `resources.Get` only works with local files, it does not load external resources.
This workaround works but it's certainly not the best way.
=> feat(sidebar): add support for external avatar

assets/scss/partials/layout/article.scss
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/85
=> fix(article): twitter_simple shortcode text color

i18n/en.yaml, i18n/ja.yaml, i18n/pt-BR.yaml, i18n/ru.yaml, i18n/tr.yaml, i18n/zh-CN.yaml, layouts/_default/archives.html
It's possible in the future to display another kind of taxonomy.
To translate that title, create _index.md under `content/categories`, with the following content:
```
---
title: Category
---
```
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/95
=> refactor(archives): remove archive.categories i18n item

layouts/_default/list.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/116
=> feat(list): display subsections in list style when there are no normal pages

assets/scss/variables.scss
If not have `monospace`, fonts will fallback to `sans-serif` when these fonts not available.
=> assets: fix font-family fallback

assets/scss/partials/layout/article.scss
Property `word-warp` in selector `.article-content code` wrap content in markdown code block like below **on masOS Safari and all iOS browsers**:
So, I removed this property to make code block the same as with other browsers like Chrome, Firefox, etc.
=> fix: remove word-wrap property for Safari

assets/scss/partials/layout/article.scss
Fixes rstudio/blogdown#591: not only `<p>` but also `<div>` could be the direct child of `.article-content`, so we also need the padding for `<div>`. The `div`s are generated by Pandoc, instead of Hugo's Markdown renderer. I think it will be great to support both ways. Thanks!
=> fix(article): also define the padding for div under .article-content

exampleSite/config.yaml, i18n/de.yaml
Added a German translation file and added German and Spanish to the option list in the main config file, as it appears to be missing
=> i18n: German translation

exampleSite/content/categories/Test/_index.md, layouts/partials/helper/image.html
In order to fix this kind of typo, the (not sophisticated) Regular Expression: `[a-zA-Z] [aA] [aeiouAEIOU]` was ran.
That Regular Expression matches some good written sentences like "a User", therefore, those has been omitted.
=> fix(typo): change 'a ex.*' for 'an ex.*'

assets/scss/partials/layout/list.scss, assets/scss/variables.scss
Change the horizontal scrollbar styles in Archives page following the dark and light themes styles.  This horizontal scrollbar is at the top of the Archives page. When I visit this page, the scrollbar stole my attention. Unfortunately, it's the client (our browser) who decides its styles;  this change is introduced to avoid that situation.
=> feat: change horizontal scrollbar styles

assets/scss/partials/layout/list.scss
The body has this transition: 'transition: background-color 0.3s ease 0s'. Setting the scrollbar-track's background-color of the horizontal scrollbar of the Archives page to transparent, will make us to appreciate that transition when switching the background-color.
=> fix: set the scrollbar-track background to transparent

assets/scss/partials/base.scss, assets/scss/partials/layout/list.scss, assets/scss/variables.scss, assets/ts/colorScheme.ts, layouts/partials/comments/provider/remark42.html, layouts/partials/comments/provider/utterances.html, layouts/partials/comments/provider/waline.html, layouts/partials/head/colorScheme.html
This change will make the _vertical_ scrollbar to follow the dark and light style modes. Also, this change will make the _vertical_ scrollbar to look consistent in both, Chromium and Firefox. 
I know we had to set the vertical scrollbar (```html { overflow-y: scroll; ...}```), even when a page doesn't have too much content to need one, to make sure the layout doesn't change when one is switching between pages. For example, in the Search page, when the search form is empty (so it doesn't need a vertical scrollbar because there is no content beyond the vertical viewport), the vertical scrollbar is still there. This change will hide that behavior as well.
=> feat: change the page vertical scrollbar styles

assets/scss/partials/layout/article.scss
=> fix(article): add `white-space: nowrap` to back button text

assets/scss/partials/article.scss, assets/scss/partials/layout/article.scss, layouts/partials/article/components/footer.html
So we can use links, e.g. to credits for main photo.
=> feat(article): use `markdownify` for licence in article

assets/scss/partials/layout/article.scss
I tried to solve this issue using this PR's approach: https://github.com/CaiJimmy/hugo-theme-stack/pull/247
But it didn't come out well, and the issue has been there for too long.
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/236
The idea is similar to this PR by @zhixuan666: #246. Thanks 👍
`75vh` is just a value that seems to be looking good.
=> feat(article): add scrollbar to toc

assets/scss/partials/layout/article.scss, assets/ts/main.ts
This button only shows on highlighted code blocks, because it uses the wrapper div.highlight. 
I didn't append the button to `<pre>` tag, because it could have overflow-x, and the button will be misplaced then.
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/264
=> feat(article): copy button for highlight block

i18n/en.yaml
I know medium.com does it the same way, but I feel like there is no need to shorten minutes as min for the articles reading time. There is enough horizontal space even on mobile devices and it is easier to read.
Also on most English websites a single short sentence is usually not terminated with a period and IMO it looks nicer without on the 404 page.
Also since you introduced line breaks for all second level YAML objects, there should be one between notFound's second-level objects too.
If you feel otherwise about all this, please feel free to close this PR or to suggest changes, as I can modify the PR or just stick to my fork for my website.
Thanks again for working on this ❤️
=> refactor(i18n): suggest improvements English translation

layouts/_default/single.html
…as accepting string "true"
It's just simple fix so it's accept a boolean true as well.
=> fix(article/comments): accept boolean `true` in `.Params.comments`

exampleSite/config.yaml
It is recommended to provide the parameter [hascjklanguage](https://gohugo.io/getting-started/configuration/#hascjklanguage) for users whose native language is Chinese/Japanese/Korean.
When the variable is true, it can make the "reading time" more accurate.
=> feat(config): add `hasCJKLanguage` parameter

exampleSite/config.yaml, layouts/partials/comments/provider/cusdis.html
Add [Cusdis](https://cusdis.com/) support.
Config descriptions are below:
```yaml
cusdis:
host: 
id: 
```
=> feat(comments): add Cusdis support

layouts/partials/comments/provider/cusdis.html
refer: https://cusdis.com/doc#/advanced/sdk
> If you are using self-hosted Cusdis, remember changing the data-host and the host in <script> to your own domain
=> fix(comments/cusdis): use the correct script for the self-hosted version

i18n/fr.yaml
Hi,
The translations for reading time was missing for French.
I think there is an issue on full date display (week days and month are still in English) if we change the format (I would like same as [here](https://gohugo.io/content-management/multilingual/#dates)). I'm not yet sure if the issue is in the theme or from my setup.
=> fix(i18n/fr): add missing translations for reading time

i18n/ko.yaml
I updated the missing part referring to en :D
- dark mode
- list-section
- list-subsction
- article-back
- article-tableOfContents
- article-readingTime
=> feat(i18n/ko): add missing translations

README.md, exampleSite/go.mod, go.mod
This PR turns the theme into a hugo module.
With `git`and `go` installed, making use of the `stack` theme is now as easy as:
```
hugo new site my_site
cd mysite
echo 'theme: "github.com/CaiJimmy/hugo-theme-stack-example"' >> config.yaml
hugo server
```
Copying/cloning the theme in the themes folder is still possible of course.
In combination with this PR I authored another [pull request](https://github.com/CaiJimmy/stack-docs/pull/9) on the `stackdocs` repo which extends the `installation` section of your documentation, explaining how to make use of the theme as module.
=> feat: turn stack theme into a hugo module

.gitignore, assets/jsconfig.json, assets/scss/partials/base.scss, assets/scss/partials/layout/article.scss, assets/ts/main.ts, assets/ts/scrollspy.ts, assets/ts/smoothAnchors.ts
A bunch of things in this PR. I'll go ahead and say right away: feel free to *not* merge this if you don't feel like this is a good change. This is something I wanted to make for my own website, and I felt like it might be a good idea to upstream these changes.
**Changes:**
- Added the Hugo build lock file to the gitignore. This is a [file added by new Hugo versions that needs to be gitignore'd](https://gohugo.io/news/0.89.0-relnotes/#notes)
- Added ES2015 as the target in `jsconfig.json`. VS Code was reporting issues from existing TS code because this was not set.
- Removed the existing `scroll-behavior: smooth` and use a custom smoothing system (`smoothAnchors.ts`). This is required because Chromium does not support smooth scrolling on both the main page via an `a` link and on another …
=> feat(article): Scrollspy for the table of contents

assets/scss/partials/base.scss, assets/scss/variables.scss
closes #474 
Removed CSS `color-scheme` property, which is introduced in #428 as fix for invisible table scrollbar. 
I changed scrollbar color to avoid that problem.
=> fix: disqus dark mode

assets/ts/gallery.ts, exampleSite/content/post/markdown-syntax/index.md, layouts/_default/_markup/render-image.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/410
The process of wrapping image with figure tag is done using JavaScript instead of only Hugo markdown render hook because it can not detect whether the image is being wrapped by a link or not and it leads to an invalid HTML construction (`<a><figure><img></figure></a>`), which is the cause of the above issue.
=> fix: hyperlinked image

layouts/_default/rss.xml
Sorry, I didn't check the result in #514.
After change in #514, all posts show in feed.
https://demo.stack.jimmycai.com/categories/syntax/index.xml
I checkout [rss.xml template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml#L1-L8) to fix this problem.
I don't sure `.Site.Params.mainSections` need `$pctx` or not.
=> fix(RSS): page context selection

assets/scss/general.scss, assets/scss/style.scss
- Move styles to general.scss, and alllow custom.scss to overwrite all style.
- Change link hover box-shadow height
from <img width="117" alt="image" src="https://user-images.githubusercontent.com/14134195/157755482-21172a34-7c36-405a-992a-fa5bd9a7f75c.png"> to <img width="121" alt="image" src="https://user-images.githubusercontent.com/14134195/157754922-d9022a8c-36a7-4a7e-94ce-1e996de2685a.png">
=> feat: add `general.scss` and change link hover style

assets/scss/partials/layout/article.scss, i18n/ar.yaml, i18n/ca.yaml, i18n/de.yaml, i18n/el.yaml, i18n/en.yaml, i18n/es.yaml, i18n/fr.yaml, i18n/id.yaml, i18n/it.yaml, i18n/ja.yaml, i18n/ko.yaml, i18n/nl.yaml, i18n/pl.yaml, i18n/pt-br.yaml, i18n/ru.yaml, i18n/th.yaml, i18n/tr.yaml, i18n/uk.yaml, i18n/zh-cn.yaml, i18n/zh-hk.yaml, i18n/zh-tw.yaml, layouts/_default/single.html, layouts/partials/article/components/related-content.html
The RELATED CONTENTS text should be RELATED CONTENT.
This is a grammar fix.
> Clone of #549
=> refactor: rename "Related contents" to "Related content"

assets/ts/smoothAnchors.ts
当文章目录为数字开头时，querySelector 无法正确选择到对应的元素。
替换为 getElementById 时能够解决此问题。
=> fix(article): TOC link not working when the heading starts with digits

assets/scss/partials/layout/article.scss, exampleSite/content/post/rich-content/index.md, layouts/shortcodes/gitlab.html
Add GitLab Snippets Shortcode #577
Also edit `twitter_simple` shortcode. The `twitter_simple` shortcode will soon require two named parameters: `user` and `id`.
=> feat(article): GitLab Snippets Shortcode

layouts/partials/article/components/details.html
Add readingTime for pages like (contact, about, etc)
To disable showing readingTime add the following param in the `frontmatter` of the article
```yml
readingTime: false
```
Notice: default value is `.Site.Params.article.readingTime`.
=> feat(article): add `readingTime` front matter field to overwrite global configuration

exampleSite/config.yaml, layouts/partials/data/description.html
This a non-breaking feature PR.
It just adds a new option to set a meta description for the website, separate from the sidebar subtitle.
The default behavior won't change, it will still fallback to the sidebar's subtitle.
=> feat: add a separate configuration field for site description

layouts/partials/sidebar/left.html
[rel="me"] is a commonly used way to show that that two websites or social media accounts are the same, and is used for authentication and proving site ownership in a variety of ways.
[rel="me"]: https://indieweb.org/rel-me
=> feat: add `rel=me` to social links

layouts/partials/article/components/details.html
=> fix(article): frontmatter field `.ReadingTime` should overwrite global configuration

layouts/partials/sidebar/left.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/682
=> fix: incorrect menu URL when baseURL is a subpath

assets/scss/partials/layout/article.scss, layouts/_default/_markup/render-codeblock.html
**Note that this is a patch for v4.**
Pass through the options of chroma highlighting processing for whom may use some options in codeblock.
<details>
<summary>Example</summary>
This feature is documented [here](https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences), but it seems not included in the exampleSite, so I use the example below.
~~~markdown
```cpp {linenos=true,hl_lines=11,linenostart=292}
float sceneSDF(vec3 p, out vec3 pColor) {
pColor = vec3(1.0, 1.0, 1.0);
vec4 pH = mk_homo(p);
vec4 pTO = mk_trans(35.0, -5.0, -20.0) * mk_scale(1.5, 1.5, 1.0) * pH;
float t1 = t1SDF(pTO.xyz);
float t2 = t2SDF((mk_trans(-45.0, 0.0, 0.0) * pTO).xyz);
float t3 = t3SDF((mk_trans(-80.0, 0.0, 0.0) * pTO).xyz);
float t4 = t4SDF((mk_trans(-106.0, 0.0, 0.0) * pTO).xyz); …
```
=> fix(codeblock): pass through the options of chroma

assets/ts/smoothAnchors.ts
Anchor links need to be decoded when using Chinese. Otherwise, the targetId-element cannot be found.
=> fix: anchor link need decode

i18n/zh-tw.yaml
Adding a `zh-tw` translation for the `footer` component which the `zh-cn` and `zh-hk` translations already have.
=> feat(i18n): add footer translation for ZH-TW

layouts/partials/article/components/math.html
This is a bug I met, and it's not difficult to fix, so I fixed it and opened this PR.
**Bug description:** 
When the gist is loaded before katex renders, the gist codes between `$` are treated by katex as math contents. (The codeblock generated by github gist is not wrapped by any `<code>` tag.) 
Below is a screenshot of such render error.
(Related gist: https://gist.github.com/Furffico/f63e63cc192d77ca3c6bb5347f0a1d63)
**Solution:**
Simply add `gist` to `ignoredClasses` option of katex configuration would fix this bug.
=> fix: KaTeX may render contents in gist under certain conditions

assets/scss/partials/sidebar.scss
=> fix(sidebar): add `padding-bottom` to the right sidebar

layouts/partials/comments/provider/remark42.html
From the [Remark42](https://remark42.com/docs/getting-started/installation/) installation guide, the code snippet right after config differs from the official guide. It needs to add `!` in front of the function.
=> fix: remark42 comment system won't show

i18n/pl.yaml
Polish language was missing the  `few` field used for numbers  2,3,4, *2,*3,*4 ((22,32,42, etc., basically a paucal form, same rules as in `ru`)
=> feat(i18n): add missing plural forms for the Polish language

exampleSite/config.yaml, layouts/partials/footer/footer.html
Thanks for this theme!! Recently migrated my site to it and am happy with the results.
Just a small irritation to save me overriding a partial, we should allow the copyright to be set independently to the site title. Reasons for this are:
- The site title might not always match the entity that owns the copyright (ie, the site title might not be an individuals or companies name).
- The `rss.xml` template calls for `.Site.Copyright` so it is required for this to render properly and it does not make sense that the option does not affect the HTML copyright as well.
I've tried to retain the original behaviour so the change is not breaking - it will use `.Site.Title` if copyright is not individually set.
Auto-generation of the date is a nice touch so of course I want to keep that as it is.
=> feat: allow footer copyright to be different to the site title

exampleSite/config.yaml, netlify.toml
New with Hugo 0.112.0
closes #853
=> fix: custom params on the language top level is deprecated

layouts/page/search.html
Avoids CORS problem when the user inputs `baseurl` incorrectly.
=> feat: use `.RelPermalink` for search JSON

assets/scss/partials/layout/article.scss
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/746
=> fix: add `word-break: break-word;` to `<a>` and `<code>`

assets/scss/partials/article.scss
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/788
=> fix: page translation links overflow

exampleSite/content/post/math-typesetting/index.md
Issue:
- Delimiters `\( some KaTeX )\` not working as math environment
Solution:
- Use delimiters `$ some KaTeX $` instead. This functionality is supported in the latest version(s) of KaTeX.
=> doc: Inline math example previously not working as intended

config.yaml
Fix the invalid parameters used in waline requiredMeta
Reference: https://waline.js.org/reference/client/props.html#commentsorting
- 类型: string[]
- 默认值: []
设置**必填项**，默认匿名，可选值:
- []
- ['nick']
- ['nick', 'mail']
=> fix: invalid params used in requiredMeta of waline

layouts/partials/comments/provider/waline.html
For example: `imageUploader` and `search` these two params will be ignored.
``` 
waline:
lang:
visitor:
imageUploader: false
search: false
avatar:
reaction: true
```
=> fix: a waline config param with false value will be ignored

assets/scss/partials/highlight/common.scss
When enable line number in codeblock, margin collapsing happens in single line code block. cause the problem in the following image. 
Add `display: block;` to `.lnt` in `assets/scss/partials/highlight/common.scss`
=> fix(article): margin collapsing in code block (firefox)

assets/scss/partials/article.scss, assets/scss/partials/layout/article.scss, assets/scss/variables.scss
有以下修改：
1. 让正文标题使用`--article-font-family`字体设置。这样的话标题和正文是一种字体，副标题和其他部分仍然是`--base-font-family`，这样也增加了标题和副标题的区分度
2. 让脚注部分的文字默认使用`--base-font-family`字体，也是便于区分脚注和正文。我感觉脚注和正文分不清是hugo目前的一大问题，并且也没有改进的计划，使用字体区分至少是一种方法
3. 让代码块中的汉字不使用默认字体而是使用`--zh-font-family`（主要针对windows，默认字体是宋体，在16px以下的时候实在是太丑了）
这些修改应该都不影响默认设置下的显示效果（因为`--article-font-family`就是`--base-font-family`）
=> feat(article): font enhancement

assets/scss/partials/menu.scss
Previously, the color of svgs in the menu were not consistent:
Fixed coloring:
All I did was add:
stroke: var(--body-text-color);
to the svg attribute in menu.scss
=> fix(menu): consistent svg coloring in menu

config/_default/params.yaml, layouts/_default/_markup/render-image.html
Add `allowedTypes` and `resizableTypes` to `imageProcessing` configuration
Prior to this commit, SVG images were not processed by `render-image.html` because SVG does not have a physical dimension like JPEG. This logic was done using a conditional.
I have now realised that Hugo can be very slow when resizing `gif` images. So I created this whitelist mechanism:
- `allowedTypes`: image types with width and height attributes
- `resizableTypes`: image types that can be resized
Here's a list of media types: bmp, gif, jpeg, png, svg+xml, tiff, webp
https://gohugo.io/templates/output-formats/#media-types
=> feat: add file types whitelist for image processing

layouts/partials/comments/provider/twikoo.html
=> fix(comments): twikoo icon & count text color not visible on dark theme

exampleSite/config.yaml, layouts/partials/head/head.html
This is caused by partialCached. It turns out that the `.RelPermalink` is the same for all pages generated by the paginator, so they will show the same title as the first page.
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/941
=> fix: title does not show pagination data

layouts/partials/sidebar/right.html
If the `params` key is not defined in the config file, you will get an error when getting any value for `.Params`:
```
nil pointer evaluating interface {}
```
This is because when the `params` key is undefined, `.Params` is nil **(note this is completely different from an empty map)**, and nil cannot be used as a map.
To fix this, just make sure `params` is always map and not nil.
=> fix(widgets): ensure `params` is not nil

layouts/partials/sidebar/left.html
Follow up to PR #950 to avoid casting Site.Home.AllTranslations to retrieve count of configured site translations.
=> fix(sidebar): translation selector - avoid cast per PR #950 

config.yaml
1. fix placeholder location
2. update url
reference: https://waline.js.org/en/cookbook/customize/locale.html
=> fix(comment): moved waline `placeholder` parameter to `locale.placeholder`

layouts/partials/sidebar/left.html
- Move `<div class="menu-bottom-section">` outside `<ol class="menu" id="main-menu">` to fix warning `<li> elements must be contained in a <ul> or <ol>`
- Add `title="language"` to language select menu to fix error `Select element must have an accessible name: Element has no title attribute`
The appearance is identical after change.
Before:
After:
=> fix(sidebar): improve accessibility of sidebar bottom menu

exampleSite/content/page/about/index.md, layouts/partials/head/opengraph/provider/base.html
This PR fixes the following deprecation warning emitted from hugo:
```
INFO  deprecated: .Site.LastChange was deprecated in Hugo v0.123.0
and will be removed in a future release. Use .Site.Lastmod instead.
```
It fixes two typos on the way as well.
=> fix: `.Site.LastChange` deprecation

assets/scss/partials/menu.scss, layouts/partials/sidebar/left.html
PR #925 moved `menu-bottom-section` outside `main-menu` which made it to disappear in mobile. This PR fixes it by moving `menu-bottom-section` back to `main-menu` as `li` and adjusting stylesheets.
Before (desktop)
After (desktop)
Before (mobile)
After (mobile)
=> fix(sidebar): menu-bottom-section not showing in mobile

layouts/partials/head/head.html
https://github.com/CaiJimmy/hugo-theme-stack/issues/922#issuecomment-1987336952
As requested, PR created with fix
=> fix: favicon does not load if baseurl includes a subfolder

layouts/partials/article/components/links.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/982
=> fix: use page resource permalink in link image

.github/ISSUE_TEMPLATE/bug_report.yml, exampleSite/hugo.yaml, layouts/partials/sidebar/left.html
A couple of the links in the project were to a doc site that seems like an old site (they didn't work) -- this PR updates those links and one that seemed like it wanted updating.
Thanks for the theme, it is grand.
=> docs: update some invalid documentation links

assets/scss/partials/menu.scss, layouts/partials/sidebar/left.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/924
=> fix: rename `.social-menu` to `.menu-social` to avoid being blocked by ad blockers

layouts/partials/article/components/math.html
Since it only accepts one element, I cannot pass `.article-content` and `#TableOfContent` to it. The official documentation uses `document.body` directly, so I guess that's fine.
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/882
=> fix: make KaTeX render all math inside `document.body`

assets/scss/partials/sidebar.scss
=> fix: rename `.social-menu` to `.menu-social` to avoid being blocked by ad blocker

layouts/partials/article/components/details.html, layouts/partials/article/components/footer.html
**Issue:**
From https://github.com/CaiJimmy/hugo-theme-stack/issues/1040
Setting `defaultContentLanguage` in `hugo.yaml` doesn't localize article publish and last modified dates.
**Proposed Solution:**
This pull request addresses the missing localization for article dates by leveraging the `time.Format` function introduced in [Hugo v0.87](https://github.com/gohugoio/hugo/releases/tag/v0.87.0).
=> fix(i18n): fix unlocalized article publish/lastUpdated date

exampleSite/hugo.yaml, layouts/partials/comments/provider/gitalk.html
I found missing proxy configuration for gitalk and added it
=> feat(comments): add support to Gitalk `proxy` parameter

exampleSite/hugo.yaml
baseURL should end in a backslash.
=> doc: add backslash to `baseURL` in exampleSite

layouts/partials/comments/provider/twikoo.html
This PR bumps Twikoo front-end to latest released version 1.6.34.
=> chore: bump Twikoo front-end to latest released version `1.6.39`

exampleSite/hugo.yaml
Related: https://github.com/CaiJimmy/hugo-theme-stack/issues/1019
=> doc: add `markup.goldmark.extensions.passthrough` in exampleSite

i18n/fr.yaml
Add translation for categories widget in french
=> fix(i18n): missing translation for title of categories widget in fr.yaml

layouts/partials/comments/provider/giscus.html
=> feat(giscus): use current language as fallback for `lang` param and add `loading` param

layouts/partials/comments/provider/giscus.html
fix https://github.com/CaiJimmy/hugo-theme-stack/issues/1083
=> fix(giscus): fallback to `en` if no language code is set

layouts/partials/article/components/math.html
When I use the waline compoment to build comment section for my blog,the comment  data couldn't pull and raise Error "Cannot read property ‘insertBefore’ of null".then I get the answer from #1044 and guess that it's due to the Katex renders before the waline compoments.
Add "waline-container` to `ignoredClasses` could work.But changing the element to render KateX may be used for most of situations,that allows each comment system to use their own Latex renderer.
Hope this helps you!
=> fix(comment/waline): cannot read property ‘insertBefore’ of null

layouts/partials/comments/provider/giscus.html
rollback #1075
closes #1117 
User can still customize the language used for Giscus using `.Site.Params.comments.giscus.lang` parameter.
=> fix(giscus): no longer use `$.Language.LanguageCode` for the language of Giscus

layouts/partials/comments/provider/disqusjs.html, layouts/partials/comments/provider/gitalk.html
Here are the refactored code snippets for both Gitalk and DisqusJS, which improve readability by using the includes() method instead of indexOf():
- Gitalk: 758dc25
- DisqusJS: 1950a66
=> refactor(comments): use `includes` instead of `indexOf` to improve readability
