exampleSite/config.toml, layouts/_default/term.html, layouts/partials/article-list/compact.html, layouts/partials/article-list/default.html, layouts/partials/article-list/tile.html, layouts/partials/article/components/details.html, layouts/partials/article/components/header.html, layouts/partials/head/opengraph.html, layouts/partials/helper/image.html
- Be able to set a default image
- Allow external featured image
- Customize the field used to get featured image
Idea: 
```javascript
interface {
exists: boolean,
resource?: resource,
permalink: string,
isDefault: boolean
}
```
=> feat(helper/image): new image helper

assets/scss/partials/layout/article.scss, layouts/404.html, layouts/_default/baseof.html, layouts/_default/list.html, layouts/_default/single.html, layouts/_default/term.html, layouts/index.html, layouts/page/archive.html, layouts/page/single.html, layouts/partials/article/article.html
=> refactor(layouts): move layout HTML to baseof.html

layouts/_default/single.html, layouts/_default/term.html, layouts/partials/article-list/compact.html, layouts/partials/article-list/default.html, layouts/partials/article-list/tile.html, layouts/partials/article/components/details.html, layouts/partials/article/components/header.html, layouts/partials/head/head.html, layouts/partials/head/opengraph/provider/base.html, layouts/partials/head/opengraph/provider/twitter.html, layouts/post/single.html
Cache some of the most invocated partials using `.RelPermalink` as cache key.
=> feat: add partialCached

exampleSite/config.toml, layouts/partials/comments/provider/utterances.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/21
=> feat(comments): add utterances support

exampleSite/config.toml
=> refactor(config): add line break between sections

layouts/partials/article/components/details.html, layouts/partials/article/components/footer.html, layouts/partials/helper/icon.html, layouts/partials/sidebar/left.html, layouts/partials/widget/archives.html, layouts/partials/widget/tag-cloud.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/32
=> feat(helper): add helper/icon

assets/scss/partials/layout/article.scss, layouts/partials/article/components/details.html, layouts/partials/article/components/tags.html, layouts/partials/widget/tag-cloud.html
=> fix: consistent style of taxonomy name

i18n/ja.toml
Let me introduce ja.toml. Thanks.
=> Japanese translation

i18n/pt-BR.toml
Add file for Brazilian Portuguese i18n
=> Add pt-BR.toml

exampleSite/config.yaml, layouts/partials/head/head.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/42
=> feat(head): add favicon setting in config.yaml

exampleSite/config.yaml, layouts/index.html, layouts/partials/footer/footer.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/55
=> feat(footer): add copyright since & custom text

layouts/_default/list.html
=> fix(list): section title style

assets/jsconfig.json, assets/ts/main.ts
ref: https://gohugo.io/news/0.78.0-relnotes/
This allows user to overwrite a specific script.
**Note: The required version of Hugo might bump up.**
=> refactor(ts): import script using new Hugo Module logic

exampleSite/config.yaml, layouts/_default/_markup/render-image.html, layouts/_default/list.html, layouts/page/search.json, layouts/partials/article-list/compact.html, layouts/partials/article-list/default.html, layouts/partials/article-list/tile.html, layouts/partials/article/components/header.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/37
=> feat: add option to disable image processing

assets/scss/grid.scss, layouts/_default/baseof.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/84
=> fix: dark mode toggle inconsistent positioning

layouts/page/search.json
- Show external image
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/92
=> fix(search): wrong permalink to page

assets/scss/partials/article.scss
Now using the same style as `.article-tags`.
=> refactor(article): improve category tag style

exampleSite/config.yaml, layouts/partials/widget/archives.html, layouts/partials/widget/search.html
related https://github.com/CaiJimmy/hugo-theme-stack/issues/106
=> feat(widget): detect automatically path to archives / search page

layouts/page/search.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/106
=> fix(search): add missing i18n text

layouts/partials/comments/provider/disqus.html, layouts/partials/comments/provider/utterances.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/107
=> fix: make Disqus / Utterances follow the global color scheme

assets/ts/colorScheme.ts
=> fix(colorScheme): dispatch onColorSchemeChange at page load

exampleSite/config.yaml, layouts/partials/comments/provider/utterances.html
Remove utterances.theme option from config.yaml
closes #117
=> fix(utterances): set color scheme on load

exampleSite/config.yaml, layouts/partials/head/head.html
Adds Google Analytics feature
It requires an Google Analytics Tracking ID in the config file.
https://gohugo.io/templates/internal/#google-analytics
=> feat: Google Analytics support

assets/scss/partials/highlight/dark.scss, assets/scss/partials/highlight/light.scss
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/126
=> fix(article): code background

data/external.yaml, layouts/partials/article/components/math.html, layouts/partials/article/components/photoswipe.html, layouts/partials/footer/components/script.html, layouts/partials/helper/external.html
Manage all external resources URL in one file
closes #78
=> feat: add data/external.yaml

layouts/_default/_markup/render-image.html, layouts/partials/helper/image.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/132
=> fix: disable svg image processing

assets/scss/partials/layout/article.scss, layouts/shortcodes/bilibili.html, layouts/shortcodes/tencent.html, layouts/shortcodes/youtube.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/165
=> refactor(article): add default padding

exampleSite/config.yaml, exampleSite/content/page/about.md, exampleSite/content/page/archives.md, exampleSite/content/page/search.md
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/151
=> refactor: add exampleSite menu using FrontMatter

layouts/_default/_markup/render-image.html, layouts/partials/helper/image.html, layouts/partials/sidebar/left.html
=> fix: incorrect image & menu path for site hosted in subdir

layouts/partials/head/opengraph/provider/twitter.html
=> refactor(opengraph/twitter): add @ before username

exampleSite/config.yaml, layouts/partials/comments/provider/vssue.html
Vssue is a Vue-powered Issue-based Comment Plugin
Support multiple code hosting services, including GitHub, GitLab, Bitbucket, Gitee and Gitea.
=> feat: add Vssue comment

i18n/ja.yaml
"サーチ" is not good translate for this situation. use "検索" instead
=> "サーチ" is not good translate

exampleSite/config.yaml, layouts/partials/head/head.html
gohugoio/hugo@ba16a14#diff-25f24f01856ed7f32bf39aafd2dcf3ebc1fb9835162d1057e2d84cb9446936c6
#209
support after v0.82.0
=> feat: Add support for Google Analytics v4

assets/scss/breakpoints.scss, assets/scss/grid.scss, assets/scss/partials/article.scss, assets/scss/partials/layout/article.scss, assets/scss/partials/menu.scss, assets/scss/partials/sidebar.scss, assets/scss/variables.scss, layouts/_default/single.html, layouts/post/single.html
Theme's stylesheet mixes the use of max-width and min-width for responsive design, and it's horrible.
And there are too many wasted spaces on small screens.
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/179
=> refactor: rewrite grid system & style changes

assets/ts/colorScheme.ts
Add HTMLElement type for toggleEl.
=> chore: add toggleEl type

i18n/fr.yaml
Also adds whitespace to match the English file's layout.
=> feat(i18n): Added missing French translations

exampleSite/config.yaml, layouts/partials/sidebar/left.html
=> feat(sidebar): add option to disable avatar in left sidebar

data/external.yaml
=> chore: update `KaTeX` to 0.13.13

assets/scss/partials/layout/article.scss, layouts/shortcodes/video.html
=> feat(article): add video shortcode

exampleSite/config.yaml, layouts/partials/comments/provider/twikoo.html
=> feat(comment): add `Twikoo` support

layouts/partials/comments/provider/twikoo.html
=> fix(comment/twikoo): submit button color

layouts/partials/comments/provider/twikoo.html
=> fix(comments): improve Twikoo style

assets/scss/partials/layout/article.scss
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/283
=> fix(article): unordered TOC style

README.md, exampleSite/config.yaml, layouts/partials/sidebar/left.html, netlify.toml
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/230
=> feat(menu): support open an entry in new tab

assets/scss/partials/layout/article.scss, layouts/partials/article/components/footer.html
=> fix(article): change `.article-time` classname to `.article-lastmod`

exampleSite/config.yaml, layouts/partials/comments/provider/giscus.html
=> feat(comments): giscus integration

assets/ts/gallery.ts, layouts/_default/_markup/render-image.html
=> refactor(article): better support for svg and external images

exampleSite/content/post/rich-content/index.md, layouts/shortcodes/bilibili.html, layouts/shortcodes/tencent.html
Mixed Content `bilibili`, `tentencent video` to https. And add bilibili shortcode example to rich content.
=> fix(shortcodes): mixed content error with bilibili and tencent video

exampleSite/config.yaml, i18n/zh-TW.yaml
=> feat(i18n): add zh-TW

assets/scss/partials/highlight/light.scss, exampleSite/content/post/markdown-syntax/index.md
closes: https://github.com/CaiJimmy/hugo-theme-stack/issues/434
=> fix: add missing diff syntax highlight

assets/jsconfig.json, assets/ts/search.tsx
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/184, https://github.com/CaiJimmy/hugo-theme-stack/pull/436
Pending
Thanks to @MassimoMaggioni 👍
=> refactor(search): avoid issue with one character keyword

assets/ts/main.ts
=> fix(shortcode): conflict with gist shortcode

assets/ts/custom.ts, layouts/partials/footer/components/script.html
允许用户在不修改主题的情况下通过 custom.ts 自定义 js 行为。
=> feat: add custom.ts

layouts/partials/sidebar/left.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/399
=> feat(sidebar): link avatar to homepage

assets/scss/partials/layout/article.scss, assets/ts/main.ts, exampleSite/config.yaml, exampleSite/content/post/rich-content/index.md
=> fix: copy code button does not work when line number is enabled

assets/icons/language.svg, assets/scss/partials/article.scss, exampleSite/config.yaml, exampleSite/content/page/about/index.cn.md, layouts/partials/article/components/details.html
=> feat(article): add link to translated content

assets/scss/grid.scss, assets/scss/partials/article.scss, assets/scss/partials/footer.scss, assets/scss/partials/layout/archives.scss, assets/scss/partials/layout/article.scss, assets/scss/partials/layout/list.scss, assets/scss/partials/layout/search.scss, assets/scss/partials/menu.scss, assets/scss/partials/pagination.scss, assets/scss/partials/sidebar.scss, assets/scss/partials/widgets.scss, assets/scss/style.scss, assets/scss/variables.scss, layouts/_default/archives.html, layouts/_default/list.html, layouts/page/search.html, layouts/partials/article/components/related-contents.html, layouts/partials/sidebar/left.html, layouts/partials/widget/search.html
=> refactor: Use flexbox gap

assets/scss/partials/menu.scss, assets/scss/partials/sidebar.scss, config.yaml, layouts/partials/sidebar/left.html
=> feat: new left sidebar layout

assets/ts/gallery.ts
fixes: https://github.com/CaiJimmy/hugo-theme-stack/discussions/522
=> fix: disable external image lightbox

layouts/_default/baseof.html
=> feat: same container width on all pages

i18n/ja.yaml, i18n/zh-CN.yaml
=> feat(i18n): add missing ja & zh-CN translations

i18n/de.yaml
Added the missing german translation for the categories widget.
=> docs(i18n): add german translation for categories widget

i18n/de.yaml, i18n/it.yaml, i18n/nl.yaml
Add missing translations for categories in the widget section.
=> feat(i18n): add missing translation (it, nl) for categories

exampleSite/config.yaml, i18n/bn.yaml
=> feat(i18n): add Bengali translation

layouts/partials/comments/provider/disqus.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/571
=> fix: check if DISQUS is loaded before accessing it

assets/scss/partials/layout/article.scss
=> fix(style): toc counter is incorrect when there are <a> in <h2>

i18n/ko.yaml
added missing korean translation (categories cloud widget)
=> feat(i18n): added missing korean translation (categories cloud widget)

layouts/partials/comments/provider/remark42.html
Updated (Remark42) frontend code taken from https://remark42.com/docs/configuration/frontend/.
Discrepancy discovered in https://github.com/umputun/remark42/discussions/1483.
=> fix(comments): update Remark42 source code

i18n/pt-pt.yaml
Very subtle changes from the Brazilian Portuguese translation
=> feat(i18n): add european portuguese translation

assets/scss/grid.scss, layouts/_default/baseof.html
=> refactor(grid): avoid sidebar layout shift when main content loads slowly

assets/scss/general.scss, assets/scss/partials/layout/article.scss
Suggested from: https://katex.org/docs/issues.html, I have tested it adding a long equation and activating a phone user agent.
=> feat(article): make long KaTeX equations scrollable in the x-axis

i18n/vi.yaml
I added Vietnamese translation.
=> feat(i18n): add vietnamese translation

layouts/partials/comments/provider/utterances.html
=> fix: the target origin mismatch recipetent window's origin

layouts/partials/comments/provider/twikoo.html
[https://github.com/imaegoo/twikoo/releases](https://github.com/imaegoo/twikoo/releases)
=> chore: update twikoo version

i18n/zh-tw.yaml
Add latest translation for zh-tw
=> feat(i18n): update translations for `zh-tw`

assets/scss/variables.scss
=> fix: very poor color contrast for default text

assets/ts/search.tsx
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/832
=> fix(search): reset `lastSearch` variable if keywords are empty

assets/scss/partials/layout/article.scss, assets/scss/variables.scss, exampleSite/config.yaml, exampleSite/content/post/markdown-syntax/index.md
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/803
=> feat(article): add style to `<kbd>` tag

i18n/nl.yaml
Added readtime translation in Dutch
=> feat(i18n): add readtime translation in Dutch

i18n/es.yaml
Less grammatical corrections because some sentences do not make sense in Spanish.
=> i18n(es): minor grammatical changes

i18n/hi.yaml
Add Hindi translation for Hindi speakers and it's my native language.
=> feat(i18n): add Hindi translation

.gitignore, i18n/be.yaml
Added translation into Belarusian language.
=> feat(i18n): add Belarusian translation

exampleSite/config.yaml
Remove deprecations. Fixes #895
=> fix(config): `site.DisqusShortname` and `site.GoogleAnalytics` are deprecated

i18n/sk.yaml
Slovak (Slovakia not Slovenia) language translation.
=> feat(i18n): add Slovak translation

i18n/ja.yaml
Update translations for Japanese.
=> feat(i18n): update translations for `ja`

layouts/_default/_markup/render-heading.html
closes https://github.com/CaiJimmy/hugo-theme-stack/issues/935
=> feat: add anchor link to markdown heading

i18n/ru.yaml, i18n/uk.yaml
Hi!
Please merge this PR.
I have aded translations for tag and category widgets.
Thanks 😉
=> feat(i18n): add translations for tag and category widgets for `ru` and `uk`

i18n/oc.yaml
Translation into Occitan language
=> feat(i18n): add Occitan translations

i18n/bg.yaml
Adding bulgarian language translation
=> feat(i18n): add Bulgarian translations

i18n/ar.yaml
بستخدام -> باستخدام
@FarisZR (main contributor to Arabic support) can confirm.
=> chore(i18n): fix a tiny typo in the footer

assets/jsconfig.json, layouts/partials/article-list/compact.html
- Fixes #1148 
This PR aims to fix a date located on compact list, which was not translated.
=> fix(article): date translation on compact mode

layouts/partials/comments/provider/waline.html
Added support for waline's turnstileKey
https://waline.js.org/reference/client/props.html#turnstilekey
=> feat(comment/waline): add support for Waline's turnstileKey
